---
apiVersion: v1
kind: Service
metadata:
  name: edgex-mongo
  labels:
    app: edgex-mongo
spec:
  type: NodePort
  ports:
  - name: "edgex-mongo"
    port: 27017
    nodePort: 32000
  selector:
    app: edgex-mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edgex-mongo
spec:
  template:
    metadata:
      labels:
        app: edgex-mongo
    spec:
      containers:
      - name: edgex-mongo
        image: edgexfoundry/docker-edgex-mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: edgex-core-consul
  labels:
    app: edgex-core-consul
spec:
  type: NodePort
  ports:
  - name: "8400"
    port: 8400
    targetPort: 8400
    nodePort: 32222
  - name: "8500"
    port: 8500
    targetPort: 8500
    nodePort: 32223
  - name: "8600"
    port: 8600
    targetPort: 8600
    nodePort: 32005
  selector:
    app: edgex-core-consul
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edgex-core-consul
spec:
  template:
    metadata:
      labels:
        app: edgex-core-consul
    spec:
      containers:
      - name: edgex-core-consul
        image: edgexfoundry/docker-core-consul:latest
        ports:
        - containerPort: 8400
        - containerPort: 8500
        - containerPort: 8600

---         
apiVersion: v1
kind: Service
metadata:
  name: edgex-core-command
  labels:
    app: edgex-core-command
spec:
  type: NodePort
  ports:
  - name: "edgex-core-command"
    port: 48082
    nodePort: 32001
  selector:
    app: edgex-core-command
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edgex-core-command
spec:
  template:
    metadata:
      labels:
        app: edgex-core-command
    spec:
      containers:
      - name: edgex-core-command
        image: edgexfoundry/docker-core-command:0.2.1
        ports:
        - containerPort: 48082
---         
apiVersion: v1
kind: Service
metadata:
  name: edgex-support-logging
  labels:
    app: edgex-support-logging
spec:
  type: NodePort
  ports:
  - name: "edgex-support-logging"
    port: 48061
    targetPort: 48061
    nodePort: 32003
  selector:
    app: edgex-support-logging
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edgex-support-logging
spec:
  template:
    metadata:
      labels:
        app: edgex-support-logging
    spec:
      containers:
      - name: edgex-support-logging
        image: edgexfoundry/docker-support-logging:0.2.1
        ports:
        - containerPort: 48061
---         
apiVersion: v1
kind: Service
metadata:
  name: edgex-core-data
  labels:
    app: edgex-core-data
spec:
  type: NodePort
  ports:
  - name: "48080"
    port: 48080
    targetPort: 48080
    nodePort: 31091
  - name: "5563"
    port: 5563
    targetPort: 5563
    nodePort: 32009
  selector:
    app: edgex-core-data
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edgex-core-data
spec:
  template:
    metadata:
      labels:
        app: edgex-core-data
    spec:
      containers:
      - name: edgex-core-data
        image: edgexfoundry/docker-core-data:0.2.1
        ports:
        - containerPort: 48080
        - containerPort: 5563
---         
apiVersion: v1
kind: Service
metadata:
  name: edgex-core-metadata
  labels:
    app: edgex-core-metadata
spec:
  type: NodePort
  ports:
  - name: "48081"
    port: 48081
    targetPort: 48081
    nodePort: 32007
  selector:
    app: edgex-core-metadata
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edgex-core-metadata
spec:
  template:
    metadata:
      labels:
        app: edgex-core-metadata
    spec:
      containers:
      - name: edgex-core-metadata
        image: edgexfoundry/docker-core-metadata:0.2.1
        ports:
        - containerPort: 48081
         

